dist: trusty
sudo: false

language: node_js
node_js:
    - node

addons:
    apt:
        packages:
            - libgconf-2-4

cache:
    directories:
        - "~/.npm"
        - "~/.cache"

script:
    - npm run lint
    - npm test
    - npm run coverage
    - npm run coveralls
    - npm run build

notifications:
    email: false

branches:
    only:
        - master
        - /^v.*$/

deploy:
    provider: npm
    email: EMAIL
    api_key:
        secure: API_KEY
    on:
        tags: true
        repo: papeloto/modaly.js
