language: node_js

node_js:
    - node

addons:
    apt:
        packages:
            - libgconf-2-4

cache:
    directories:
        - node_modules
        - ~/.npm
        - ~/.cache

script:
    - npm run lint
    - npm run build
    - npm test

notifications:
    email: false
